# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: baltagod
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ReceiptPython

provider:
  name: aws
  runtime: python3.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::pdfreceiptbucketforiicnose/*"

functions:
  hello:
    handler: handler.hello
